import type { Metadata } from 'next';
import './globals.css';
import { CookiePortal } from '@/ui';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={styles.body}>
        {children}
        <div id="cookie-portal" />
        <CookiePortal />
      </body>
    </html>
  );
}
